const Certificate = [
    {
        id: "1",
        title: "HackerRank Certified Problem Solving (Intermediate)",
        slug: "HackerRank Certified Problem Solving (Intermediate)",
        organization: "HackerRank",
        image: '/certificates/ProblemSolvingIntermediate.PNG',
        issue_date: "26 Jan 2025",
        expiration_date: "Does not expire",
        credential_id: "E7831B1FDB11",
        created_at: "26 Jan 2025",
        updated_at: "26 Jan 2025",
        link: "https://www.hackerrank.com/certificates/E7831B1FDB11",
    },
    {
        id: "2",
        title: "HackerRank Certified JavaScript (Intermediate)",
        slug: "HackerRank Certified JavaScript (Intermediate)",
        organization: "HackerRank",
        image: '/certificates/JavascriptIntermediate.PNG',
        issue_date: "25 Jan 2025",
        expiration_date: "Does not expire",
        credential_id: "02D60D597EB2",
        created_at: "25 Jan 2025",
        updated_at: "25 Jan 2025",
        link: "https://www.hackerrank.com/certificates/02D60D597EB2"
    },
    {
        id: "3",
        title: "HackerRank Certified Frontend Developer (React)",
        slug: "HackerRank Certified Frontend Developer (React)",
        organization: "HackerRank",
        image: '/certificates/FrontendDeveloperReact.PNG',
        issue_date: "24 Jan 2025",
        expiration_date: "Does not expire",
        credential_id: "EF9415D1759E",
        created_at: "24 Jan 2025",
        updated_at: "24 Jan 2025",
        link: "https://www.hackerrank.com/certificates/EF9415D1759E"
    },
    {
        id: "4",
        title: "Blockchain Fundamentals",
        slug: "Blockchain Fundamentals",
        organization: "Chainlink",
        image: '/certificates/blockchain-fundamentals-certification.png',
        issue_date: "05 May 2025",
        expiration_date: "06 May 2026",
        credential_id: "d67fd917-1f71-4df2-86fe-5a61935a75ac",
        created_at: "05 May 2025",
        updated_at: "05 May 2025",
        link: "https://www.credly.com/badges/d67fd917-1f71-4df2-86fe-5a61935a75ac/public_url"
    },
    {
        id: "5",
        title: "Artificial Intelligence Fundamentals",
        slug: "Artificial Intelligence Fundamentals",
        organization: "IBM SkillsBuild",
        image: '/certificates/AI-fundamentals-certification.png',
        issue_date: "06 Oct 2025",
        expiration_date: "07 Oct 2026",
        credential_id: "b7015e46-46b3-4b6a-bde5-d8c1ba1c7bb7",
        created_at: "06 Oct 2025",
        updated_at: "06 Oct 2025",
        link: "https://www.credly.com/badges/b7015e46-46b3-4b6a-bde5-d8c1ba1c7bb7/public_url"
    },
    {
        id: "6",
        title: "HackerRank Certified Node.js (Intermediate)",
        slug: "HackerRank Certified Node.js (Intermediate)",
        organization: "HackerRank",
        image: '/certificates/NodejsIntermediate.PNG',
        issue_date: "25 Jan 2025",
        expiration_date: "Does not expire",
        credential_id: "388034A6E711",
        created_at: "25 Jan 2025",
        updated_at: "25 Jan 2025",
        link: "https://www.hackerrank.com/certificates/388034A6E711"
    },
    {
        id: "7",
        title: "HackerRank Certified Rest API (Intermediate)",
        slug: "HackerRank Certified Rest API (Intermediate)",
        organization: "HackerRank",
        image: '/certificates/RestAPIIntermediate.PNG',
        issue_date: "26 Jan 2025",
        expiration_date: "Does not expire",
        credential_id: "98FA1416141C",
        created_at: "26 Jan 2025",
        updated_at: "26 Jan 2025",
        link: "https://www.hackerrank.com/certificates/98FA1416141C"
    },
    {
        id: "8",
        title: "HackerRank Certified SQL (Advanced)",
        slug: "HackerRank Certified SQL (Advanced)",
        organization: "HackerRank",
        image: '/certificates/SQLAdvanced.PNG',
        issue_date: "27 Jan 2025",
        expiration_date: "Does not expire",
        credential_id: "0EAE5B50AC8B",
        created_at: "27 Jan 2025",
        updated_at: "27 Jan 2025",
        link: "https://www.hackerrank.com/certificates/0EAE5B50AC8B"
    },
    {
        id: "9",
        title: "HackerRank Certified Python (Basic)",
        slug: "HackerRank Certified Python (Basic)",
        organization: "HackerRank",
        image: '/certificates/PythonBasic.PNG',
        issue_date: "28 Jan 2025",
        expiration_date: "Does not expire",
        credential_id: "462373EAD5B1",
        created_at: "28 Jan 2025",
        updated_at: "28 Jan 2025",
        link: "https://www.hackerrank.com/certificates/462373EAD5B1"
    },
    {
        id: "10",
        title: "HackerRank Certified Software Engineer",
        slug: "HackerRank Certified Software Engineer",
        organization: "HackerRank",
        image: '/certificates/SoftwareEngineer.PNG',
        issue_date: "26 Jan 2025",
        expiration_date: "Does not expire",
        credential_id: "3B73E30D28A6",
        created_at: "26 Jan 2025",
        updated_at: "26 Jan 2025",
        link: "https://www.hackerrank.com/certificates/3B73E30D28A6"
    }
];

export default Certificate;