const Certificate = [
    {
        id: "1",
        title: "HackerRank Certified Problem Solving (Basic)",
        slug: "HackerRank Certified Problem Solving (Basic)",
        organization: "HackerRank",
        image: '/certificates/ProblemSolvingBasic.PNG',
        issue_date: "24 Jan 2025",
        expiration_date: "Does not expire",
        credential_id: "350A6A3F72F1",
        created_at: "24 Jan 2025",
        updated_at: "24 Jan 2025",
    },
    {
        id: "2",
        title: "HackerRank Certified JavaScript (Intermediate)",
        slug: "HackerRank Certified JavaScript (Intermediate)",
        organization: "HackerRank",
        image: '/certificates/JavascriptIntermediate.PNG',
        issue_date: "25 Jan 2025",
        expiration_date: "Does not expire",
        credential_id: "02D60D597EB2",
        created_at: "25 Jan 2025",
        updated_at: "25 Jan 2025",
    },
    {
        id: "3",
        title: "HackerRank Certified Frontend (React)",
        slug: "HackerRank Certified Frontend (React)",
        organization: "HackerRank",
        image: '/certificates/FrontendDeveloperReact.PNG',
        issue_date: "24 Jan 2025",
        expiration_date: "Does not expire",
        credential_id: "EF9415D1759E",
        created_at: "24 Jan 2025",
        updated_at: "24 Jan 2025",
    },
    {
        id: "4",
        title: "HackerRank Certified Node.js (Intermediate)",
        slug: "HackerRank Certified Node.js (Intermediate)",
        organization: "HackerRank",
        image: '/certificates/NodejsIntermediate.PNG',
        issue_date: "25 Jan 2025",
        expiration_date: "Does not expire",
        credential_id: "A328DC98Q",
        created_at: "25 Jan 2025",
        updated_at: "25 Jan 2025",
    }
];

export default Certificate;