const Experience = [
    {
        id: 1,
        slug: "Freelancing",
        company: "Freelancing",
        company_image: "/images/companies/upwork.png",
        company_url: "https://upwork.com",
        address: "Remote",
        designation: "Full stack Blockchain Developer",
        job_type: "Full Time",
        job_location_type: "Remote",
        start_date: "May 2020",
        end_date: "Oct 2021",
        duration: "May 2020 - Oct 2021",
        duration_in_days: "1 year, 5 months",
        currently_working: "string",
        description: `
        <p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;">Developed the DePIN project analytics site utilizing GraphQL, Apollo, Dune Query, Cron Job scheduling, Redis caching, MonoRepo architecture, and Atomic design leveraging a broad network of connections with CEOs.</span></p>
        <p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;">Developed a NYW NFT marketplace on multichain - Ethereum and Solana like OpenSea utilizing Next.js, Nodejs, PostgreSQL, Subgraph for full stack development and Solidity and Hardhat, Rust and Anchor for Smart contract development.</span></p>
        <p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;">Developed a Solana Trading bot using Typescript, Solana/Web3.js, Jito, bloXroute, Raydium SDK and Telegram API</span></p></div>`,
        created_at: "string",
        updated_at: "string",
    },
    {
        id: 2,
        slug: "Luxfi",
        company: "Luxfi",
        company_image: "/images/companies/luxfy.png",
        company_url: "https://lux.link",
        address: "Hong Kong",
        designation: "Senior Blockchain Engineer",
        job_type: "Full Time",
        job_location_type: "Remote",
        start_date: "Aug 2023",
        end_date: "May 2024",
        duration: "Aug 2023 - May 2024",
        duration_in_days: "10 months",
        currently_working: "string",
        description: `<div class="relative md:border-gray-300 md:dark:border-gray-400 md:col-span-4 text-sm text-inherit font-light pt-6"><p class="MsoListParagraphCxSpFirst" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]-->&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora; font-weight: bold; font-size: 16px; margin-bottom: 5px">   As a senior Blockchain developer, I have mainly worked on the development of a Vulcan ICO Launchpad and Turbo Trade Cross-chain AMM/ DEX platform from scratch using Cosmos SDK, Bifrost protocol, Maya chain.</span></p></div>`,
        created_at: "string",
        updated_at: "string",
    },
    {
        id: 3,
        slug: "RUBY Exchange",
        company: "RUBY Exchange",
        company_image: "/images/companies/rubyexchange.svg",
        company_url: "https://ruby.exchange/",
        address: "Flughafen, Zürich, Switzerland",
        designation: "Smart Contract Developer",
        job_type: "Full Time",
        job_location_type: "Hybrid",
        start_date: "Jun 2022",
        end_date: "Jun 2023",
        duration: "Jun 2022 - Jun 2023",
        duration_in_days: "1 year, 1 months",
        currently_working: "string",
        description: `<div class="relative md:border-gray-300 md:dark:border-gray-400 md:col-span-4 text-sm text-inherit font-light pt-6"><p class="MsoListParagraphCxSpFirst" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]-->&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora; font-weight: bold; font-size: 16px; margin-bottom: 5px">DEX platform for crypto trading on Ethergem blockchain.</span></p>
        <p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;">Wrote several smart contracts for various DeFi functionalities like adding/ removing liquidity pools, token swaps and staking mechanisms.</span></p>
        <p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;">Conducted thorough testing and audits to identify and fix vulnerabilities ensuring the platform worked securely.</span></p>
        <p class="MsoListParagraphCxSpMiddle" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;"><span style="mso-list: Ignore;">●<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora;">Used Redux as state management, TailwindCSS and MUI for UI styling.</span></p></div>`,
        created_at: "string",
        updated_at: "string",
    },
    {
        id: 4,
        slug: "AutoTroph",
        company: "AutoTroph",
        company_image: "/images/companies/autotroph.png",
        company_url: "https://autotrophit.com/",
        address: "Marlborough Hill Harrow, London, United Kingdom",
        designation: "Frontend Developer",
        job_type: "Full Time",
        job_location_type: "Remote",
        start_date: "Jul 2021",
        end_date: "Apr 2022",
        duration: "Jul 2021 - Apr 2022",
        duration_in_days: "10 months",
        currently_working: "string",
        description: `<div class="relative md:border-gray-300 md:dark:border-gray-400 md:col-span-4 text-sm text-inherit font-light pt-6"><p class="MsoListParagraphCxSpFirst" style="text-indent: -.25in; mso-list: l0 level1 lfo1;"><!-- [if !supportLists]-->&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span lang="EN" style="font-family: Lora; mso-fareast-font-family: Lora; mso-bidi-font-family: Lora; font-weight: bold; font-size: 16px; margin-bottom: 5px">As a junior Frontend developer, I participated in the development of Bolly Gaming casino games like slots, aviator, coin-flip, lucky-spin games using MERN, Pixijs and AWS.</span></p></div>`,
        created_at: "string",
        updated_at: "string",
    },
];

export default Experience;