const MyProfile = {
    id: 1,
    username: "marksantiago",
    email: "marksantiago0929@gmail.com",
    name: "Mark Santiago",
    slug: "marksantiago",
    nickname: "BTC415",
    gender: "M",
    image: '/images/Mark.png',
    dob: "string",
    website: "string",
    contact: "string",
    contact_email: "marksantiago0929@gmail.com",
    linkedin: "https://www.linkedin.com/in/mark-santiago-373172339/",
    github: "https://github.com/BTC415",
    address: "Block 9 Lot 16 Coral Street Phase 4 Mansfield Sto. Domingo, Angeles City, Central Luzon, Philippines",
    about: "string",
    is_portfolio_user: "string",
    // resume_link: "https://docs.google.com/document/d/1l57bPBavQkU9wgTKRfe_7wS9UYWj8aS0n-yXMHqIikk/edit?tab=t.0",
    is_active: "string",
    is_staff: "string",
    is_superuser: "string",
    date_joined: "6 Jul 2024",
    last_login: "6 Jul 2024",
    updated_at: "6 Jul 2024",
};

export default MyProfile;