const Project = [
    {
        id: "1",
        title: "NYW NFT Marketplace",
        slug: "NYWNFTMarketplace",
        image: '/images/Projects/NYWNFT.PNG',
        short_description: "NFT Marketplace",
        technology: "Blockchain, NFT, marketplace, Smart Contract",
        duration: "May 2024 ~ Aug 2024",
        duration_in_days: "4 Months",
        preview_url: "https://nyw-marketplace.vercel.app/",
        github_url: "https://github.com/BTC415/NYW-NFT-frontend",
        description: "New York World NFT is a unique and multi - chain marketplace specializing in super rare NFTs(Non-Fungible Token) and crypto-collectibles",
        created_at: "05 May 2024",
        updated_at: "25 Aug 2024",
    },
    {
        id: "2",
        title: "Vulcan Launchpad",
        slug: "VulcanLaunchpad",
        image: '/images/Projects/vulcan.PNG',
        short_description: "ICO Launchpad",
        technology: "Blockchain, ICO, Launchpad, Smart Contract",
        duration: "May 2023 ~ Oct 2023",
        duration_in_days: "6 Months",
        preview_url: "https://vulcanpad.tech/",
        github_url: "https://github.com/BTC415/SilverPad_Contract",
        description: "Vulcan Launchpad is a Crowd Funding System for multi-chain eco system",
        created_at: "19 May 2023",
        updated_at: "11 Oct 2023",
    },
    {
        id: "3",
        title: "TurboTrade",
        slug: "TurboTrade",
        image: '/images/Projects/turbo.PNG',
        short_description: "A DeFi Platform",
        technology: "Blockchain, NFT, marketplace, Smart Contract",
        duration: "Oct 2023 ~ Mar 2024",
        duration_in_days: "4 Months",
        preview_url: "https://app.turbotrade.tech/",
        github_url: "https://github.com/BTC415/TurboTrade",
        description: "Turbo Trade is a DeFi platform that facilitates easy wallet connectivity, efficient token swapping, and liquidity management.",
        created_at: "25 Oct 2023",
        updated_at: "19 Mar 2024",
    },
    {
        id: "4",
        title: "BollyGaming Casino Game",
        slug: "BollyGamingCasinoGame",
        image: '/images/Projects/VVSL.PNG',
        short_description: "A B2B Casino Game Platform",
        technology: "Casino Game, B2B, Slot Game, Aviator, Lucky Wheel, Heads or Tails",
        duration: "Jul 2021 ~ Apr 2022",
        duration_in_days: "10 Months",
        preview_url: "https://lobbyuat.bollygaming.games/slot/mbsl/?token=c42ca54b-0e44-4348-95c5-f0c058334847",
        github_url: "https://github.com/BTC415/Casino_slot",
        description: "A casino slot games, aviator, lucky wheel, heads or tails game using React and Pixijs",
        created_at: "05 Jul 2021",
        updated_at: "25 Apr 2022",
    }    
];

export default Project;