const Project = [
    {
        id: "1",
        title: "NYW NFT Marketplace",
        slug: "NYWNFTMarketplace",
        image: '/images/Projects/NYWNFT.PNG',
        short_description: "NFT Marketplace",
        technology: "Blockchain, NFT, marketplace, Smart Contract",
        duration: "May 2024 ~ Aug 2024",
        duration_in_days: "4 Months",
        preview_url: "https://nyw-marketplace.vercel.app/",
        github_url: "https://github.com/BTC415/NYW-NFT-frontend",
        description: "New York World NFT is a unique and multi - chain marketplace specializing in super rare NFTs(Non-Fungible Token) and crypto-collectibles",
        created_at: "05 May 2024",
        updated_at: "25 Aug 2024",
    },
    {
        id: "2",
        title: "Vulcan Launchpad",
        slug: "VulcanLaunchpad",
        image: '/images/Projects/vulcan.PNG',
        short_description: "ICO Launchpad",
        technology: "Blockchain, ICO, Launchpad, Smart Contract",
        duration: "May 2023 ~ Oct 2023",
        duration_in_days: "6 Months",
        preview_url: "https://vulcanpad.tech/",
        github_url: "https://github.com/BTC415/SilverPad_Contract",
        description: "Vulcan Launchpad is a Crowd Funding System for multi-chain eco system",
        created_at: "19 May 2023",
        updated_at: "11 Oct 2023",
    },
    {
        id: "3",
        title: "TurboTrade",
        slug: "TurboTrade",
        image: '/images/Projects/turbo.PNG',
        short_description: "A DeFi Platform",
        technology: "Blockchain, NFT, marketplace, Smart Contract",
        duration: "Oct 2023 ~ Mar 2024",
        duration_in_days: "5 Months",
        preview_url: "https://app.turbotrade.tech/",
        github_url: "https://github.com/BTC415/TurboTrade",
        description: "Turbo Trade is a DeFi platform that facilitates easy wallet connectivity, efficient token swapping, and liquidity management.",
        created_at: "25 Oct 2023",
        updated_at: "19 Mar 2024",
    },
    {
        id: "4",
        title: "Xion",
        slug: "Xion",
        image: '/images/Projects/xion.png',
        short_description: "A DeFi Platform",
        technology: "Blockchain, NFT, marketplace, Smart Contract",
        duration: "Oct 2022 ~ Feb 2023",
        duration_in_days: "4 Months",
        preview_url: "https://xion.app/home",
        github_url: "https://github.com/BTC415/xion_finance",
        description: "XION a DeFi Global cross-chain Staking - cryto shopping up to 100% cashback rewards.",
        created_at: "03 Oct 2023",
        updated_at: "23 Feb 2024",
    },
    {
        id: "5",
        title: "EventSmarter",
        slug: "EventSmarter",
        image: '/images/Projects/eventsmarter.jpg',
        short_description: "Onsite Event Check-in Software",
        technology: "React, Node.js, MongoDB, Express.js, Socket.io",
        duration: "Aug 2022 ~ Sep 2022",
        duration_in_days: "4 Months",
        preview_url: "https://www.eventssmarter.com/",
        github_url: "https://github.com/BTC415/eventsmarter",
        description: "Events Smarter is a platform designed for the entertainment and event industries that facilitates ticket buying and selling.",
        created_at: "03 Aug 2022",
        updated_at: "29 Sep 2022",
    },
    
    {
        id: "7",
        title: "BollyGaming Casino Game",
        slug: "BollyGamingCasinoGame",
        image: '/images/Projects/VVSL.png',
        short_description: "A B2B Casino Game Platform",
        technology: "Casino Game, B2B, Slot Game, Aviator, Lucky Wheel, Heads or Tails",
        duration: "Jul 2021 ~ Apr 2022",
        duration_in_days: "10 Months",
        preview_url: "https://lobbyuat.bollygaming.games/slot/mbsl/?token=c42ca54b-0e44-4348-95c5-f0c058334847",
        github_url: "https://github.com/BTC415/Casino_slot",
        description: "A casino slot games, aviator, lucky wheel, heads or tails game using React and Pixijs",
        created_at: "05 Jul 2021",
        updated_at: "25 Apr 2022",
    },
    {
        id: "8",
        title: "BollyGaming Casino Game",
        slug: "BollyGamingCasinoGame",
        image: '/images/Projects/aviator.png',
        short_description: "A B2B Casino Game Platform",
        technology: "Casino Game, B2B, Slot Game, Aviator, Lucky Wheel, Heads or Tails",
        duration: "Jul 2021 ~ Apr 2022",
        duration_in_days: "10 Months",
        preview_url: "https://lobbyuat.bollygaming.games/aviator/?token=c42ca54b-0e44-4348-95c5-f0c058334847",
        github_url: "https://github.com/BTC415/Casino_slot",
        description: "A casino slot games, aviator, lucky wheel, heads or tails game using React and Pixijs",
        created_at: "05 Jul 2021",
        updated_at: "25 Apr 2022",
    }    
];

export default Project;